package main

import (
	"fmt"
	"os"
	"os/signal"

	"github.com/robfig/cron"
)

func main() {
	fmt.Println(" * * * Welcome to an istance of a tiny docker image generated by damdo/gobin * * * ")
	fmt.Println("This is an example code with an external dependency to demonstrate the auto dependency installation capabilities")
	c := cron.New()
	c.AddFunc("* * * * * *", func() { fmt.Println("This function runs Every second thanks to github.com/robfig/cron") })
	go c.Start()

	sig := make(chan os.Signal)
	signal.Notify(sig, os.Interrupt, os.Kill)
	<-sig
}
